const target=document.getElementById("detail"),code=new URLSearchParams(location.search).get("code"),records=JSON.parse(FMSStorage.getItem("fms-stock-records")||"[]"),record=records.find(item=>String(item.code||"")===String(code||"")),escapeHtml=value=>String(value??"-").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
if(!record){target.innerHTML="<h1>ไม่พบข้อมูลสินค้านี้</h1>"}else{const name=record.name||record.productName||"รายการยา",remaining=Math.max(0,(Number(record.total)||0)-(Number(record.used)||0));target.innerHTML=`<h1>${escapeHtml(name)}${record.genericName?`<br><span>(${escapeHtml(record.genericName)})</span>`:""}</h1><div class="detail-image">${record.image?`<img src="${record.image}" alt="${escapeHtml(name)}">`:`<span class="empty-image">รูปภาพสินค้า</span>`}</div><div class="details"><h2>รายละเอียดของสินค้า</h2><p><strong>ชื่อสินค้า:</strong> ${escapeHtml(record.productName)}</p><p><strong>ชื่อสามัญ:</strong> ${escapeHtml(record.genericName)}</p><p><strong>ประเภท:</strong> ${escapeHtml({oral:"ยากิน",topical:"ยาทา",equipment:"เวชภัณฑ์"}[record.category]||record.category)}</p><p><strong>รหัสยา:</strong> ${escapeHtml(record.code)}</p><p><strong>รูปแบบ:</strong> ${escapeHtml(record.form)}</p><p><strong>ขนาด:</strong> ${escapeHtml(record.size)}</p><p><strong>หน่วยนับ:</strong> ${escapeHtml(record.unit)}</p><p><strong>สรรพคุณ:</strong> ${escapeHtml(record.benefit)}</p><p><strong>อาการที่ใช้:</strong> ${escapeHtml(record.symptom)}</p><p><strong>วิธีใช้:</strong> ${escapeHtml(record.usage)}</p><p><strong>ข้อควรระวัง:</strong> ${escapeHtml(record.warning)}</p><p><strong>วันหมดอายุ:</strong> ${escapeHtml(record.expiry)}</p></div><section class="catalog-stock"><h2>สถานะสินค้าในคลัง</h2><div class="stock-values"><div class="total"><label>ทั้งหมด</label><strong>${Number(record.total)||0}</strong></div><div class="used"><label>ใช้ไป</label><strong>${Number(record.used)||0}</strong></div><div class="remaining"><label>เหลือ</label><strong>${remaining}</strong></div></div></section><div class="detail-actions"><button id="detailAddToCart" class="detail-cart-button" type="button">🛒 เพิ่มลงตะกร้า</button></div>`}
document.querySelector(".language")?.addEventListener("click",()=>{const english=document.documentElement.lang!=="en";document.documentElement.lang=english?"en":"th";document.querySelector(".language span").textContent=english?"English":"ไทย"});
document.getElementById("exportPdf")?.addEventListener("click",()=>window.print());
document.getElementById("exportExcel")?.addEventListener("click",()=>{if(!record)return;const rows=[["Name","Code","Category","Total","Used","Remaining"],[record.name||record.productName||"",record.code||"",record.category||"",record.total||0,record.used||0,Math.max(0,(Number(record.total)||0)-(Number(record.used)||0))]],csv=rows.map(row=>row.join(",")).join("\n"),link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));link.download=`${record.code||"catalog-item"}.csv`;link.click();URL.revokeObjectURL(link.href)});
const detailAddToCart=document.getElementById("detailAddToCart");detailAddToCart?.addEventListener("click",()=>{if(!record)return;const cart=JSON.parse(FMSStorage.getItem("fms-catalog-cart")||"{}");cart[record.code]=cart[record.code]||{quantity:0};cart[record.code].quantity=Math.min(100,(Number(cart[record.code].quantity)||0)+1);FMSStorage.setItem("fms-catalog-cart",JSON.stringify(cart));detailAddToCart.textContent="✓ เพิ่มแล้ว";detailAddToCart.classList.add("added")});const bell=document.getElementById("notificationButton");
const notification=document.getElementById("notificationPanel");bell?.addEventListener("click",()=>{notification.hidden=!notification.hidden});document.getElementById("closeNotification")?.addEventListener("click",()=>{notification.hidden=true});document.head.insertAdjacentHTML("beforeend","<style>.notification-panel{position:fixed;z-index:10;right:1rem;top:4.5rem;width:min(20rem,calc(100vw - 2rem));padding:1rem;border:1px solid #91b2ff;border-radius:.7rem;background:#fff;box-shadow:0 .8rem 2rem #0003;color:#07164f}.notification-panel button{float:right;border:0;background:transparent;font-size:1.2rem;cursor:pointer}.notification-panel p{margin:.5rem 0 0;color:#53617a}</style>");


