const records=JSON.parse(localStorage.getItem("fms-stock-records")||"[]"),cartKey="fms-catalog-cart",cart=JSON.parse(localStorage.getItem(cartKey)||"{}"),selected=new Set(Object.keys(cart));
const list=document.getElementById("cartList"),total=document.getElementById("cartTotal"),selectAll=document.getElementById("selectAll"),modal=document.getElementById("confirmModal"),modalTitle=document.getElementById("modalTitle"),modalCancel=document.getElementById("modalCancel"),modalConfirm=document.getElementById("modalConfirm");let pendingDelete=false;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem(cartKey,JSON.stringify(cart))}
function count(){return Object.values(cart).filter(item=>(Number(item.quantity)||0)>0).length}
function render(){const items=Object.keys(cart).map(code=>{const item=records.find(row=>String(row.code)===String(code))||{code,name:code};return{...item,quantity:Number(cart[code].quantity)||0}}).filter(item=>item.quantity>0);total.textContent=`(${count()})`;list.innerHTML=items.length?items.map(item=>`<article class="cart-row"><input type="checkbox" data-select="${esc(item.code)}" ${selected.has(String(item.code))?"checked":""}><div class="cart-image">${item.image?`<img src="${item.image}" alt="${esc(item.name||item.productName)}">`:`<div class="cart-empty-image">รูปภาพสินค้า</div>`}</div><div class="cart-info"><strong>${esc(item.name||item.productName||"รายการยา")}</strong><small>รหัสยา: ${esc(item.code)}</small>${cart[item.code].option?`<small>ตัวเลือก: ${esc(cart[item.code].option)}</small>`:""}<small>${esc(item.symptom||"อาการทั่วไป")}</small></div><div class="cart-quantity"><button type="button" data-delta="-1" data-code="${esc(item.code)}">−</button><input type="number" min="1" value="${item.quantity}" data-quantity="${esc(item.code)}"><button type="button" data-delta="1" data-code="${esc(item.code)}">＋</button></div></article>`).join(""):"<div class=\"cart-empty-state\">ยังไม่มีสินค้าในรถเข็น</div>";selectAll.checked=items.length>0&&items.every(item=>selected.has(String(item.code)))}
function openDeleteModal(){pendingDelete=true;modalTitle.textContent=`ต้องการลบสินค้า ${selected.size} ชิ้นหรือไม่`;modal.hidden=false}
function closeDeleteModal(){pendingDelete=false;modal.hidden=true}
const confirmDelete=()=>{if(!pendingDelete)return;selected.forEach(code=>delete cart[code]);selected.clear();save();render();closeDeleteModal()};modalCancel.onclick=closeDeleteModal;modalConfirm.onclick=confirmDelete;modalCancel.addEventListener("click",closeDeleteModal,{capture:true});modalConfirm.addEventListener("click",confirmDelete,{capture:true});modal.addEventListener("click",event=>{if(event.target===modal)closeDeleteModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&pendingDelete)closeDeleteModal()});
list.addEventListener("change",e=>{const checkbox=e.target.closest("[data-select]");if(checkbox){checkbox.checked?selected.add(checkbox.dataset.select):selected.delete(checkbox.dataset.select);render()}const input=e.target.closest("[data-quantity]");if(input){cart[input.dataset.quantity].quantity=Math.max(1,Number(input.value)||1);save();render()}});
list.addEventListener("click",e=>{const button=e.target.closest("[data-delta]");if(!button)return;const code=button.dataset.code;cart[code].quantity=Math.max(1,(Number(cart[code].quantity)||1)+Number(button.dataset.delta));save();render()});
selectAll.addEventListener("change",()=>{Object.keys(cart).forEach(code=>selectAll.checked?selected.add(code):selected.delete(code));render()});
document.getElementById("deleteSelected").addEventListener("click",()=>{if(!selected.size)return;openDeleteModal()});document.getElementById("placeOrder").addEventListener("click",()=>{if(Object.keys(cart).some(code=>(Number(cart[code].quantity)||0)>0))location.href="./catalog-order.html"});document.getElementById("clearCart").addEventListener("click",()=>{if(!Object.keys(cart).length)return;selected.clear();Object.keys(cart).forEach(code=>selected.add(code));openDeleteModal()});
document.querySelector(".language")?.addEventListener("click",()=>{const english=document.documentElement.lang!=="en";document.documentElement.lang=english?"en":"th";document.querySelector(".language span").textContent=english?"English":"ไทย"});render();
// PDF/Excel fallback for the cart detail page.
document.querySelectorAll(".topbar .export").forEach((button) => button.addEventListener("click", () => window.print()));
