const calendar = document.getElementById("dutyCalendar"), calendarMonth = document.getElementById("calendarMonth"), startDate = document.getElementById("startDate"), endDate = document.getElementById("endDate"), languageButton = document.getElementById("languageButton"), languageLabel = document.getElementById("languageLabel"), resetButton = document.getElementById("resetButton"), facultySelect = document.getElementById("facultySelect"), branchInput = document.getElementById("branchInput"), notificationButton = document.getElementById("notificationButton"), notificationBadge = document.getElementById("notificationBadge"), notificationPanel = document.getElementById("notificationPanel"), notificationList = document.getElementById("notificationList"), markNotificationsRead = document.getElementById("markNotificationsRead"), exportExcel = document.getElementById("exportExcel"), exportPdf = document.getElementById("exportPdf");
let language = "th", notificationsRead = false;
const genderStats = { male: 0, female: 0 }, referralStats = { total: 0, hospitals: [] };
const medicineDetails = {}, medicineDetailEnglish = {}, medicineStatusTotals = { expired: 0, expiring: 0, low: 0, normal: 0 }, medicinePageSize = 10, medicineModalState = { status: "expired", page: 0, index: 0 };
const translations = { th: { overview: "ภาพรวมแดชบอร์ด", dateRange: "ช่วงวันที่", dateTo: "ถึงวันที่", faculty: "หลักสูตร", branch: "สาขา", all: "ทั้งหมด", reset: "รีเซ็ต", visitTrend: "แนวโน้มการเข้าใช้ห้องพยาบาล", notifications: "การแจ้งเตือน", markRead: "อ่านทั้งหมด", topMedicines: "Top 10 ยาที่ใช้มากที่สุด", symptoms: "สัดส่วนอาการที่พบ", duty: "ประวัติการสั่ง", stock: "สถานะสต็อกยา", expiredStock: "ยาหมดอายุแล้ว", expiringStock: "ใกล้หมดอายุ (ภายใน 30 วัน)", lowStock: "ยาและเวชภัณฑ์ต่ำกว่า Min Stock", normalStock: "ยาและเวชภัณฑ์ปกติ", expiry: "ยาใกล้หมดอายุ", expired: "หมดอายุแล้ว", within30: "ภายใน 30 วัน", within3Months: "1–3 เดือน", gender: "เปรียบเทียบเพศ", male: "ชาย", female: "หญิง", cases: "เคส", referrals: "การส่งต่อโรงพยาบาล", topHospitals: "โรงพยาบาลที่เข้าบ่อยที่สุด 3 อันดับ", items: "รายการ", week: ["อา.", "จ.", "อ.", "พ.", "พฤ.", "ศ.", "ส."], symptomsList: ["ปวดศีรษะ", "ไข้", "ปวดท้อง", "แผลถลอก", "เวียนศีรษะ"] }, en: { overview: "Overview Dashboard", dateRange: "Date range", dateTo: "To date", faculty: "Faculty", branch: "Branch", all: "All", reset: "Reset", visitTrend: "Infirmary visit trend", notifications: "Notifications", markRead: "Mark all read", topMedicines: "Top 10 most used medicines", symptoms: "Common symptoms", duty: "Order history", stock: "Medicine stock status", expiredStock: "Expired medicines & supplies", expiringStock: "Expiring soon (within 30 days)", lowStock: "Below minimum stock", normalStock: "Normal medicine stock", expiry: "Medicine expiry status", expired: "Expired", within30: "Within 30 days", within3Months: "1–3 months", gender: "Gender comparison", male: "Male", female: "Female", cases: "Cases", referrals: "Hospital referrals", topHospitals: "Top 3 most visited hospitals", items: "items", week: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"], symptomsList: ["Headache", "Fever", "Stomachache", "Abrasions", "Dizziness"] } };
const facultyBranches = {
  all: ["วิศวกรรมไฟฟ้า แขนงไฟฟ้ากำลัง", "วิศวกรรมไฟฟ้า แขนงอิเล็กทรอนิกส์และไฟฟ้าสื่อสาร", "วิศวกรรมหุ่นยนต์และอิเล็กทรอนิกส์อัจฉริยะ", "วิศวกรรมเครื่องกล", "วิศวกรรมคอมพิวเตอร์", "วิศวกรรมอุตสาหการและการผลิต", "วิศวกรรมโยธา", "เทคโนโลยีการจัดการผลิตพืช / เทคโนโลยีการผลิตพืชด้วยศาสตร์พระราชา", "สัตวศาสตร์ แขนงการผลิตและธุรกิจปศุสัตว์", "สัตวศาสตร์ แขนงการผลิตและธุรกิจสัตว์เลี้ยง", "วิทยาศาสตร์การประมงและทรัพยากรทางน้ำ", "บริหารธุรกิจและการเป็นผู้ประกอบการ", "นวัตกรรมอาหารและการจัดการ"],
  engineering: ["วิศวกรรมไฟฟ้า แขนงไฟฟ้ากำลัง", "วิศวกรรมไฟฟ้า แขนงอิเล็กทรอนิกส์และไฟฟ้าสื่อสาร", "วิศวกรรมหุ่นยนต์และอิเล็กทรอนิกส์อัจฉริยะ", "วิศวกรรมเครื่องกล", "วิศวกรรมคอมพิวเตอร์", "วิศวกรรมอุตสาหการและการผลิต", "วิศวกรรมโยธา"],
  agriculture: ["เทคโนโลยีการจัดการผลิตพืช / เทคโนโลยีการผลิตพืชด้วยศาสตร์พระราชา", "สัตวศาสตร์ แขนงการผลิตและธุรกิจปศุสัตว์", "สัตวศาสตร์ แขนงการผลิตและธุรกิจสัตว์เลี้ยง", "วิทยาศาสตร์การประมงและทรัพยากรทางน้ำ"],
  business: ["บริหารธุรกิจและการเป็นผู้ประกอบการ", "นวัตกรรมอาหารและการจัดการ"]
};
const facultyLabels = { engineering: { th: "หลักสูตรวิศวกรรมศาสตร์", en: "Faculty of Engineering" }, agriculture: { th: "หลักสูตรเทคโนโลยีการเกษตรและวิทยาศาสตร์", en: "Faculty of Agricultural Technology and Science" }, business: { th: "หลักสูตรบริหารธุรกิจและนวัตกรรม", en: "Faculty of Business Administration and Innovation" } };
const branchLabels = { "วิศวกรรมไฟฟ้า แขนงไฟฟ้ากำลัง": "Electrical Engineering · Power Engineering", "วิศวกรรมไฟฟ้า แขนงอิเล็กทรอนิกส์และไฟฟ้าสื่อสาร": "Electrical Engineering · Electronics and Communication", "วิศวกรรมหุ่นยนต์และอิเล็กทรอนิกส์อัจฉริยะ": "Robotics and Smart Electronics Engineering", "วิศวกรรมเครื่องกล": "Mechanical Engineering", "วิศวกรรมคอมพิวเตอร์": "Computer Engineering", "วิศวกรรมอุตสาหการและการผลิต": "Industrial and Production Engineering", "วิศวกรรมโยธา": "Civil Engineering", "เทคโนโลยีการจัดการผลิตพืช / เทคโนโลยีการผลิตพืชด้วยศาสตร์พระราชา": "Plant Production Management Technology / Royal Agricultural Science", "สัตวศาสตร์ แขนงการผลิตและธุรกิจปศุสัตว์": "Animal Science · Livestock Production and Business", "สัตวศาสตร์ แขนงการผลิตและธุรกิจสัตว์เลี้ยง": "Animal Science · Pet Production and Business", "วิทยาศาสตร์การประมงและทรัพยากรทางน้ำ": "Fisheries Science and Aquatic Resources", "บริหารธุรกิจและการเป็นผู้ประกอบการ": "Business Administration and Entrepreneurship", "นวัตกรรมอาหารและการจัดการ": "Food Innovation and Management" };
function displayBranch(name) { return language === "en" ? (branchLabels[name] || name) : name; }
function localizeFacultyOptions() { Array.from(facultySelect.options).forEach((option) => { option.textContent = option.value === "all" ? translations[language].all : facultyLabels[option.value]?.[language] || option.textContent; }); rebuildCustomSelect(facultySelect); }
function syncCustomSelect(select) { const wrapper = select.closest(".custom-select"); if (!wrapper) return; const current = select.options[select.selectedIndex]; wrapper.querySelector(".custom-select-value").textContent = current?.textContent || translations[language].all; wrapper.querySelectorAll("[data-custom-value]").forEach((option) => { option.classList.toggle("is-selected", option.dataset.customValue === select.value); }); }
function rebuildCustomSelect(select) { const wrapper = select.closest(".custom-select"); if (!wrapper) return; const menu = wrapper.querySelector(".custom-select-menu"); menu.innerHTML = Array.from(select.options).map((option) => `<button type="button" role="option" class="custom-select-option${option.value === select.value ? " is-selected" : ""}" data-custom-value="${option.value}">${option.textContent}</button>`).join(""); syncCustomSelect(select); }
function enhanceCustomSelect(select) { if (select.closest(".custom-select")) return; const wrapper = document.createElement("div"); wrapper.className = "custom-select"; select.parentNode.insertBefore(wrapper, select); wrapper.appendChild(select); select.hidden = true; wrapper.insertAdjacentHTML("beforeend", `<button type="button" class="custom-select-trigger" aria-haspopup="listbox" aria-expanded="false"><span class="custom-select-value"></span><svg class="custom-select-chevron" viewBox="0 0 20 20" aria-hidden="true"><path d="M5.75 7.5 10 11.75 14.25 7.5" /></svg></button><div class="custom-select-menu" role="listbox" hidden></div>`); const trigger = wrapper.querySelector(".custom-select-trigger"); trigger.addEventListener("click", () => { const open = wrapper.classList.toggle("is-open"); trigger.setAttribute("aria-expanded", String(open)); wrapper.querySelector(".custom-select-menu").hidden = !open; }); wrapper.addEventListener("click", (event) => { const option = event.target.closest("[data-custom-value]"); if (!option) return; select.value = option.dataset.customValue; select.dispatchEvent(new Event("change", { bubbles: true })); wrapper.classList.remove("is-open"); trigger.setAttribute("aria-expanded", "false"); wrapper.querySelector(".custom-select-menu").hidden = true; syncCustomSelect(select); }); rebuildCustomSelect(select); }
function renderBranchOptions() { const selected = branchInput.value, values = facultyBranches[facultySelect.value] || facultyBranches.all; branchInput.innerHTML = [`<option value="all">${translations[language].all}</option>`, ...values.map((name) => `<option value="${name.replace(/"/g, "&quot;")}">${displayBranch(name)}</option>`)].join(""); branchInput.value = values.includes(selected) ? selected : "all"; rebuildCustomSelect(branchInput); }
let calendarViewDate = new Date();
function parseInputDate(value) { return value ? new Date(`${value}T00:00:00`) : null; }
function renderCalendar() { if (!calendarMonth || !calendar) return; const year = calendarViewDate.getFullYear(), month = calendarViewDate.getMonth(), firstDay = new Date(year, month, 1).getDay(), daysInMonth = new Date(year, month + 1, 0).getDate(), selectedStart = parseInputDate(startDate.value), selectedEnd = parseInputDate(endDate.value); calendarMonth.textContent = new Intl.DateTimeFormat(language === "th" ? "th-TH" : "en-US", { month: "long", year: "numeric" }).format(calendarViewDate); const blanks = Array.from({ length: firstDay }, () => "<span class=\"blank\"></span>").join(""); const days = Array.from({ length: daysInMonth }, (_, index) => { const date = new Date(year, month, index + 1); const inRange = selectedStart && selectedEnd && date >= selectedStart && date <= selectedEnd; const isStart = selectedStart && date.getTime() === selectedStart.getTime(); const isEnd = selectedEnd && date.getTime() === selectedEnd.getTime(); return `<span class=\"${inRange ? "is-range" : ""}${isStart || isEnd ? " is-selected" : ""}\">${index + 1}</span>`; }).join(""); calendar.innerHTML = blanks + days; }
function getNotifications() { return []; }
function renderNotifications() { notificationList.replaceChildren(); notificationBadge.hidden = true; notificationBadge.textContent = "0"; }
function renderLanguage() { const t = translations[language], panelTitles = [t.topMedicines, t.symptoms, t.stock, t.expiry, t.gender, t.referrals]; document.documentElement.lang = language; document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t[element.dataset.i18n]; }); document.querySelectorAll(".medicine-panel .panel-title,.symptom-panel .panel-title,.status-panel .panel-title,.expiry .panel-title,.gender .panel-title,.referrals .panel-title").forEach((element, index) => { element.textContent = panelTitles[index]; }); document.querySelectorAll(".calendar-week span").forEach((element, index) => { element.textContent = t.week[index]; }); document.querySelectorAll(".bars b").forEach((element, index) => { element.textContent = t.week[index + 1] || t.week[0]; }); document.querySelectorAll(".stock b").forEach((element, index) => { element.textContent = [t.expiredStock, t.expiringStock, t.lowStock, t.normalStock][index]; }); document.querySelectorAll(".expiry-legend span").forEach((element, index) => { element.textContent = [t.expired, t.within30, t.within3Months][index]; }); document.querySelectorAll(".gender-row b").forEach((element, index) => { element.textContent = index === 0 ? t.male : t.female; }); document.querySelectorAll(".gender-row small,.referral-main small").forEach((element) => { element.textContent = t.cases; }); document.querySelector(".referral-heading").textContent = t.topHospitals; document.querySelector(".medicine-picker-label").firstChild.nodeValue = language === "th" ? "เลือกรายการยา" : "Select medicine"; document.querySelector(".medicine-expiry span").textContent = language === "th" ? "วันหมดอายุ" : "Expiry date"; document.querySelectorAll(".medicine-stock-grid span").forEach((element, index) => { element.textContent = language === "th" ? ["สต็อกทั้งหมด", "ใช้ไปแล้ว", "คงเหลือ"][index] : ["Total stock", "Used", "Remaining"][index]; }); languageLabel.textContent = language === "th" ? "ไทย" : "English"; if (!facultySelect.value) facultySelect.value = "all"; localizeFacultyOptions(); renderBranchOptions(); renderStockCounts(); renderNotifications(); renderCalendar(); if (document.getElementById("medicineDetailModal").open) renderMedicineDetail(); }
function renderGenderStats() { document.getElementById("maleCount").textContent = "0"; document.getElementById("femaleCount").textContent = "0"; }
function renderReferralStats() { document.getElementById("referralCount").childNodes[0].nodeValue = "0"; document.getElementById("referralList").replaceChildren(); }
function getMedicineList() { return []; }
function renderMedicineDetail() {}
function showMedicineDetail() {}
function renderStockCounts() { document.querySelectorAll(".stock-detail-button").forEach((button) => { button.closest(".stock").querySelector("small").textContent = `0 ${translations[language].items}`; }); }
async function captureDashboard() { return window.html2canvas(document.querySelector("main.page"), { scale: 2, useCORS: true, backgroundColor: "#e5e7ff", logging: false }); }
function downloadBlob(blob, filename) { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
async function downloadPdf() { window.print(); }
const pieTooltip = document.createElement("div");
pieTooltip.className = "pie-tooltip";
document.body.appendChild(pieTooltip);

function polarPoint(angle) { const rad = (angle - 90) * Math.PI / 180; return [50 + 50 * Math.cos(rad), 50 + 50 * Math.sin(rad)]; }
function piePath(start, end) { const [x1, y1] = polarPoint(start), [x2, y2] = polarPoint(end); return `M 50 50 L ${x1} ${y1} A 50 50 0 ${end - start > 180 ? 1 : 0} 1 ${x2} ${y2} Z`; }
function renderInteractivePie(elementId, data) {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.setAttribute("viewBox", "0 0 100 100"); svg.setAttribute("role", "img");
  let start = 0;
  data.forEach((item) => { const end = start + item.percent * 3.6; const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.setAttribute("d", piePath(start, end)); path.setAttribute("fill", item.color); path.setAttribute("tabindex", "0"); path.setAttribute("aria-label", `${item.name}: ${item.percent}%`); const show = (event) => { pieTooltip.textContent = `${item.name}: ${item.percent}%`; pieTooltip.style.left = `${event.clientX + 14}px`; pieTooltip.style.top = `${event.clientY + 14}px`; pieTooltip.hidden = false; }; path.addEventListener("pointermove", show); path.addEventListener("pointerenter", show); path.addEventListener("pointerleave", () => { pieTooltip.hidden = true; }); path.addEventListener("focus", () => { pieTooltip.textContent = `${item.name}: ${item.percent}%`; pieTooltip.hidden = false; }); path.addEventListener("blur", () => { pieTooltip.hidden = true; }); svg.appendChild(path); start = end; });
  document.getElementById(elementId).replaceChildren(svg);
}
function donutPath(start, end) { const [x1, y1] = polarPoint(start), [x2, y2] = polarPoint(end); const inner = 27, toInner = (angle) => { const rad = (angle - 90) * Math.PI / 180; return [50 + inner * Math.cos(rad), 50 + inner * Math.sin(rad)]; }, [ix1, iy1] = toInner(start), [ix2, iy2] = toInner(end), large = end - start > 180 ? 1 : 0; return `M ${x1} ${y1} A 50 50 0 ${large} 1 ${x2} ${y2} L ${ix2} ${iy2} A ${inner} ${inner} 0 ${large} 0 ${ix1} ${iy1} Z`; }
function renderInteractiveDonut(elementId, data) { const container = document.getElementById(elementId), svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.setAttribute("viewBox", "0 0 100 100"); let start = 0; data.forEach((item) => { const end = start + item.percent * 3.6, path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.setAttribute("d", donutPath(start, end)); path.setAttribute("fill", item.color); const show = (event) => { pieTooltip.textContent = `${item.name}: ${item.count} รายการ (${item.percent}%)`; pieTooltip.style.left = `${event.clientX + 14}px`; pieTooltip.style.top = `${event.clientY + 14}px`; pieTooltip.hidden = false; }; path.addEventListener("pointermove", show); path.addEventListener("pointerenter", show); path.addEventListener("pointerleave", () => { pieTooltip.hidden = true; }); svg.appendChild(path); start = end; }); container.querySelector("svg")?.remove(); container.prepend(svg); }
languageButton.addEventListener("click", (event) => { event.preventDefault(); language = language === "th" ? "en" : "th"; renderLanguage(); });
function syncCalendarToRange() { const selected = parseInputDate(startDate.value) || parseInputDate(endDate.value); if (selected) calendarViewDate = selected; renderCalendar(); }
startDate.addEventListener("change", syncCalendarToRange); endDate.addEventListener("change", syncCalendarToRange);
resetButton.addEventListener("click", () => { startDate.value = ""; endDate.value = ""; facultySelect.value = "all"; branchInput.value = "all"; syncCustomSelect(facultySelect); renderBranchOptions(); calendarViewDate = new Date(); renderCalendar(); });
facultySelect.addEventListener("change", renderBranchOptions);
enhanceCustomSelect(facultySelect); enhanceCustomSelect(branchInput);
document.addEventListener("click", (event) => { document.querySelectorAll(".custom-select.is-open").forEach((wrapper) => { if (!wrapper.contains(event.target)) { wrapper.classList.remove("is-open"); wrapper.querySelector(".custom-select-trigger")?.setAttribute("aria-expanded", "false"); const menu = wrapper.querySelector(".custom-select-menu"); if (menu) menu.hidden = true; } }); });
notificationButton.addEventListener("click", () => { notificationPanel.hidden = !notificationPanel.hidden; }); markNotificationsRead.addEventListener("click", () => { notificationsRead = true; renderNotifications(); }); document.addEventListener("click", (event) => { if (!notificationPanel.hidden && !notificationPanel.contains(event.target) && !notificationButton.contains(event.target)) notificationPanel.hidden = true; }); exportExcel.addEventListener("click", () => window.downloadLiveDashboardExcel?.()); exportPdf.addEventListener("click", downloadPdf); renderGenderStats(); renderReferralStats(); renderStockCounts(); renderCalendar(); renderLanguage();
document.querySelectorAll(".stock-detail-button").forEach((button) => button.addEventListener("click", () => showMedicineDetail(button.dataset.medicineStatus))); document.getElementById("closeMedicineModal").addEventListener("click", () => document.getElementById("medicineDetailModal").close()); document.getElementById("medicinePicker").addEventListener("change", (event) => { medicineModalState.index = Number(event.target.value); renderMedicineDetail(); }); document.getElementById("medicinePrevPage").addEventListener("click", () => { medicineModalState.page -= 1; medicineModalState.index = medicineModalState.page * medicinePageSize; renderMedicineDetail(); }); document.getElementById("medicineNextPage").addEventListener("click", () => { medicineModalState.page += 1; medicineModalState.index = medicineModalState.page * medicinePageSize; renderMedicineDetail(); });



document.head.insertAdjacentHTML("beforeend", '<link rel="stylesheet" href="./dashboard-topbar.css?v=2">');
