const form=document.getElementById("visitForm"),languageButton=document.getElementById("languageButton"),noticeButton=document.getElementById("noticeButton"),notificationPanel=document.getElementById("notificationPanel"),closeNotifications=document.getElementById("closeNotifications"),visitorOptions=[...document.querySelectorAll(".visitor-option")],visitorDetail=document.getElementById("visitorDetail"),statusChecks=[...document.querySelectorAll(".status input")],referralHospital=document.getElementById("referralHospitalField"),message=document.getElementById("formMessage");let language="th",visitorType="";
const text={th:{title:"บันทึกการเข้าห้องพยาบาล",typeInfo:"รอบระเบียบ",historyLink:"ดูประวัติ",formTitle:"ฟอร์มการเข้าใช้ห้องพยาบาล",student:"บุคลากรภายใน",studentHint:"เช่น อาจารย์, นักศึกษา",guest:"บุคลากรภายนอก",guestHint:"เช่น ผู้รับเหมา, ผู้มาติดต่อ",firstName:"ชื่อ",lastName:"นามสกุล",nickname:"ชื่อเล่น",age:"อายุ",studentId:"รหัสนักศึกษา",branch:"สาขา",gender:"เพศ",blood:"กรุ๊ปเลือด",weight:"น้ำหนัก",height:"ส่วนสูง",symptom:"อาการ",vitals:"ผลการวัดความดัน",medicine:"ยาที่ได้รับ",quantity:"จำนวนยา /หน่วย",status:"สถานะ",normal:"ปกติ",observe:"รอดูอาการ",refer:"ส่งโรงพยาบาล",cancel:"ยกเลิก",save:"บันทึก",saved:"บันทึกข้อมูลการเข้าห้องพยาบาลเรียบร้อย"},en:{title:"Infirmary Visit",typeInfo:"Visit type",historyLink:"View history",formTitle:"Infirmary visit form",student:"Internal visitor",studentHint:"e.g. teacher, student",guest:"External visitor",guestHint:"e.g. contractor, visitor",firstName:"First name",lastName:"Last name",nickname:"Nickname",age:"Age",studentId:"Student ID",branch:"Department",gender:"Gender",blood:"Blood type",weight:"Weight",height:"Height",symptom:"Symptoms",vitals:"Vital signs",medicine:"Medicine given",quantity:"Medicine quantity",status:"Status",normal:"Normal",observe:"Observation",refer:"Hospital referral",cancel:"Cancel",save:"Save",saved:"Infirmary visit saved"}};
function renderLanguage(){const t=text[language];document.documentElement.lang=language;document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t[el.dataset.i18n]);languageButton.querySelector("span").textContent=language==="th"?"ไทย":"English"}
noticeButton.addEventListener("click",()=>{notificationPanel.hidden=!notificationPanel.hidden;noticeButton.setAttribute("aria-expanded",String(!notificationPanel.hidden))});closeNotifications.addEventListener("click",()=>{notificationPanel.hidden=true;noticeButton.setAttribute("aria-expanded","false")});
const statusColors={normal:"#2f9e55",observe:"#e99a1f",refer:"#db4545"};function updateStatusColor(current){if(current.checked){statusChecks.forEach(item=>{if(item!==current)item.checked=false});form.style.setProperty("--status-shadow",statusColors[current.value])}else{form.style.setProperty("--status-shadow","#c5c6ca")}const isRefer=current.checked&&current.value==="refer",hospitalInput=referralHospital.querySelector("input");referralHospital.hidden=!isRefer;hospitalInput.disabled=!isRefer;hospitalInput.required=isRefer;if(isRefer)hospitalInput.focus()}statusChecks.forEach(item=>item.addEventListener("change",()=>updateStatusColor(item)));
function syncReferralHospital(){const refer=statusChecks.find(item=>item.value==="refer"),hospitalInput=referralHospital.querySelector("input"),isRefer=refer.checked;referralHospital.hidden=!isRefer;referralHospital.style.display=isRefer?"block":"none";hospitalInput.disabled=!isRefer;hospitalInput.required=isRefer;if(isRefer)hospitalInput.focus()}form.querySelector(".status").after(referralHospital);form.addEventListener("click",event=>{if(event.target.closest(".status label"))setTimeout(syncReferralHospital,0)});statusChecks.forEach(item=>item.addEventListener("change",syncReferralHospital));
form.addEventListener("reset",()=>setTimeout(()=>{form.style.setProperty("--status-shadow","#c5c6ca");const hospitalInput=referralHospital.querySelector("input");referralHospital.hidden=true;referralHospital.style.display="none";hospitalInput.disabled=true;hospitalInput.required=false},0));
visitorOptions.forEach(option=>option.querySelector(".visitor-check").addEventListener("change",event=>{const checked=event.target.checked;visitorOptions.forEach(item=>{const selected=item===option&&checked;item.querySelector(".visitor-check").checked=selected;item.classList.toggle("is-selected",selected)});visitorType=checked?option.dataset.type:"";visitorDetail.disabled=!checked;visitorDetail.name=visitorType==="guest"?"visitorDetailExternal":"visitorDetail";visitorDetail.placeholder=visitorType==="guest"?"เช่น ผู้รับเหมา, ผู้มาติดต่อ":visitorType==="student"?"เช่น อาจารย์, นักศึกษา":"เลือกประเภทบุคลากรก่อน";if(!checked)visitorDetail.value="";document.querySelector("[name=studentId]").disabled=visitorType==="guest";document.querySelector("[name=studentId]").placeholder=visitorType==="guest"?"ไม่จำเป็น":""}));
languageButton.addEventListener("click",()=>{language=language==="th"?"en":"th";renderLanguage()});document.getElementById("cancelButton").addEventListener("click",()=>{message.textContent="";visitorType="";visitorOptions.forEach(item=>{item.classList.remove("is-selected");item.querySelector(".visitor-check").checked=false});visitorDetail.disabled=true;visitorDetail.value="";visitorDetail.placeholder="เลือกประเภทบุคลากรก่อน"});form.addEventListener("submit",event=>{event.preventDefault();if(!visitorType){message.textContent=language==="th"?"กรุณาเลือกประเภทบุคลากรก่อนบันทึก":"Please select a visitor type before saving";message.style.color="#c43a3a";return}const selectedStatus=statusChecks.find(item=>item.checked)?.value;if(!selectedStatus){message.textContent=language==="th"?"กรุณาเลือกสถานะก่อนบันทึก":"Please select a status before saving";message.style.color="#c43a3a";return}const record={...Object.fromEntries(new FormData(form)),visitorType,createdAt:new Date().toISOString()};const records=JSON.parse(localStorage.getItem("fms-infirmary-visits")||"[]");records.unshift(record);localStorage.setItem("fms-infirmary-visits",JSON.stringify(records));window.location.href=selectedStatus==="observe"?"./pending-assessment.html":"./infirmary-visit-history.html"});renderLanguage();
// PDF/Excel fallback for the infirmary visit detail page.
document.querySelectorAll(".topbar .export").forEach((button) => button.addEventListener("click", () => window.print()));

const medicineSelect = form.querySelector('select[name="medicine"]');
function readStockMedicineNames() {
  try {
    const records = JSON.parse(localStorage.getItem("fms-stock-records") || "[]");
    return Array.from(new Set(records.map((record) => record.name || record.productName || record.genericName).filter(Boolean)));
  } catch {
    return [];
  }
}
function renderMedicineOptions() {
  if (!medicineSelect) return;
  const selected = medicineSelect.value;
  const stockNames = readStockMedicineNames();
  const fallbackNames = ["Paracetamol 500 mg", "ORS", "Cetirizine 10 mg"];
  const names = stockNames.length ? stockNames : fallbackNames;
  medicineSelect.innerHTML = `<option value="">${language === "th" ? "เลือกยา" : "Select medicine"}</option>${names.map((name) => `<option value="${String(name).replace(/"/g, "&quot;")}">${String(name).replace(/[&<>]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[char]))}</option>`).join("")}`;
  if (names.includes(selected)) medicineSelect.value = selected;
}
renderMedicineOptions();
window.addEventListener("storage", (event) => { if (event.key === "fms-stock-records") renderMedicineOptions(); });
window.addEventListener("focus", renderMedicineOptions);
languageButton.addEventListener("click", () => setTimeout(renderMedicineOptions, 0));
