"use client";
import Link from 'next/link';
import { useEffect, useState, useCallback } from 'react';
import { api, authClient, mutate, Account } from '../../lib/client';
type Row=Record<string,any>;
type Field=[string,string,string?,string[]?];
const drugFields:Field[]=[['name','??????'],['productName','??????????'],['genericName','?????????'],['category','??????','select',['oral','topical','equipment']],['form','??????'],['size','????'],['unit','?????'],['total','???????','number'],['used','???/????','number'],['expiry','??????????','date'],['benefit','???????'],['symptom','?????'],['usage','???????'],['warning','???????'],['reason','????????????????']];
const visitFields:Field[]=[['visitorType','????????????','select',['??????????','???????????']],['visitorDetail','??????????????????????'],['firstName','????'],['lastName','???????'],['nickname','????????'],['age','????','number'],['studentId','????????????'],['faculty','????????','faculty'],['branch','????','branch'],['gender','???','select',['???','????']],['blood','?????????','select',['A','B','AB','O']],['weight','???????','number'],['height','???????','number'],['symptom','?????'],['sys','SYS','number'],['dia','DIA','number'],['pr','PR','number'],['status','?????','select',['normal','observe','refer']],['hospitalName','???????????????']];
const loanFields:Field[]=[['fullName','??????????'],['nickname','????????'],['studentId','????????????'],['phone','????????'],['faculty','????????','faculty'],['branch','????','branch'],['department','????????'],['activity','???????'],['reason','??????'],['role','????????????'],['dueDate','????????','date']];
const dutyFields:Field[]=[['date','??????','date'],['color','??','select',Array.from({length:50},(_,i)=>`color-${i+1}`)],['firstName','????'],['lastName','???????'],['nickname','????????'],['affiliation','??????']];
const titles:Record<string,string>={stock:'??????',catalog:'??????????????????????','infirmary-visit':'?????????????????','borrow-return':'???????','duty-shift':'????????',activity:'???????????????',settings:'???????????????',dashboard:'Dashboard ?????????'};
const endpoints:Record<string,string>={stock:'medicines',catalog:'catalog-orders','infirmary-visit':'infirmary-visits','borrow-return':'loans','duty-shift':'duties',activity:'medicines/movements',settings:'settings',dashboard:'dashboard'};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const inputClass='mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2 text-slate-900';
export default function Workspace({slug}:{slug:string}) {
  const [user,setUser]=useState<Account|null>(null),[rows,setRows]=useState<Row[]>([]),[meds,setMeds]=useState<Row[]>([]),[references,setReferences]=useState<Row[]>([]),[users,setUsers]=useState<Row[]>([]),[audit,setAudit]=useState<Row[]>([]),[summary,setSummary]=useState<Row|null>(null);
  const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[form,setForm]=useState<Row|null>(null),[selection,setSelection]=useState<Row[]>([]),[detail,setDetail]=useState<Row|null>(null);
  const [start,setStart]=useState(()=>new Date(Date.now()-29*86400000).toISOString().slice(0,10)),[end,setEnd]=useState(today),[faculty,setFaculty]=useState('all'),[branch,setBranch]=useState('all');
  const [refName,setRefName]=useState(''),[refCode,setRefCode]=useState(''),[refFaculty,setRefFaculty]=useState('');
  const load=useCallback(async()=>{
    const auth=await authClient();const current=await auth.me();if(!current){location.replace('/login');return;}setUser(current);
    if(slug==='settings'&&current.role!=='ADMIN')throw Error('????????????????');
    const [medicine,settings,result]=await Promise.all([api<Row[]>('medicines'),api<Row>('settings'),api(endpoints[slug]+(slug==='dashboard'?'?'+new URLSearchParams({start,end,faculty,branch}):''))]);
    setMeds(medicine);setReferences(settings.faculties);
    if(slug==='dashboard')setSummary(result);else if(slug!=='settings')setRows(result);
    if(slug==='settings'){const [accounts,logs]=await Promise.all([api<Row[]>('admin/users'),api<Row[]>('admin/audit?limit=100')]);setUsers(accounts);setAudit(logs);}
  },[slug,start,end,faculty,branch]);
  useEffect(()=>{let active=true;setLoading(true);load().catch(e=>active&&setMessage(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[load]);
  useEffect(()=>{if(slug!=='dashboard')return;const timer=setInterval(()=>load().catch(e=>setMessage('??????????????????: '+e.message)),30000);return()=>clearInterval(timer);},[slug,load]);
  async function work(action:()=>Promise<unknown>,close=false){if(busy)return;setBusy(true);setMessage('');try{await action();if(close){setForm(null);setSelection([]);}await load();setMessage('??????????');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  function open(row?:Row){setMessage('');setDetail(null);setForm(row?{...row,...(slug==='stock'?{image:undefined}:{}),dueDate:row.dueDate?.slice(0,10)}:{category:'oral',visitorType:'??????????',status:'observe',total:0,used:0,date:today(),color:'color-1',dueDate:today(),documentTitle:'',orderId:crypto.randomUUID()});setSelection((row?.dispensations||[]).map((i:Row)=>({medicineId:i.medicineId,quantity:i.quantity})));}
  async function save(event:React.FormEvent){event.preventDefault();if(!form)return;const data={...form};
    await work(async()=>{
      if(slug==='stock')await mutate('medicines'+(data.id?'/'+data.id:''),data.id?'PATCH':'POST',data);
      if(slug==='infirmary-visit')await mutate('infirmary-visits'+(data.id?'/'+data.id:''),data.id?'PATCH':'POST',{...data,dispensations:selection});
      if(slug==='borrow-return')await mutate('loans','POST',{details:data,dueDate:data.dueDate,items:selection});
      if(slug==='catalog')await mutate('catalog-orders','POST',{id:data.orderId,documentTitle:data.documentTitle,items:selection.map(i=>{const m=meds.find(m=>m.id===i.medicineId)!;return {code:m.code,name:m.name,unit:m.unit,image:m.imageUrl,quantity:i.quantity};})});
      if(slug==='duty-shift'){await mutate('nurses/me','POST',{...data,colorId:data.color});await mutate('duties','POST',data);}
    },true);
  }
  const fields=slug==='stock'?drugFields:slug==='infirmary-visit'?visitFields:slug==='borrow-return'?loanFields:slug==='duty-shift'?dutyFields:[['documentTitle','??????????']] as Field[];
  const visible=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())&&(status==='all'||r.status===status||slug==='stock'&&(status==='active'?r.active:!r.active)));
  const medicineOptions=meds.filter(m=>m.active&&(!m.expiry||m.expiry>=today())&&m.remaining>0);
  function line(row:Row){return (row.dispensations||row.items||[]).map((i:Row)=>`${i.name||i.code} ${i.quantity} ${i.unit||''}`).join(', ');}
  function downloadCsv(){const columns=slug==='stock'?['code','name','unit','total','used','remaining','expiry','imageUrl']:slug==='infirmary-visit'?['createdAt','firstName','lastName','symptom','status','hospitalName','????????']:['id','createdAt','fullName','documentTitle','date','dueDate','status','????????'];const cell=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const body=[columns.map(cell).join(','),...visible.map(row=>columns.map(c=>cell(c==='????????'?line(row):row[c])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+body],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`fms-${slug}.csv`;a.click();URL.revokeObjectURL(url);}
  const button=(label:string,onClick:()=>void,disabled=false)=><button type="button" className="rounded-lg border border-cyan-700 px-3 py-2 text-cyan-900 disabled:opacity-40" disabled={disabled||busy} onClick={onClick}>{label}</button>;
  if(!titles[slug])return null;
  return <main className="mx-auto max-w-7xl space-y-5 p-6 text-slate-800"><nav className="flex flex-wrap gap-3 print:hidden"><Link href="/">? ????</Link>{Object.entries(titles).filter(([k])=>k!=='settings'||user?.role==='ADMIN').map(([k,v])=><Link key={k} href={'/modules/'+k}>{v}</Link>)}{button('??????????',()=>{authClient().then(a=>a.logout()).then(()=>location.href='/login');})}</nav><h1 className="text-3xl font-bold text-cyan-900">{titles[slug]}</h1><p role="status" className="text-red-700">{loading?'????????????????':message}</p>
    {!loading&&<>
    <div className="flex flex-wrap gap-3 print:hidden">{button('??????',()=>work(load))}{!['dashboard','settings','activity'].includes(slug)&&button(slug==='catalog'?'???????????????':'???????????',()=>open())}{button('?????? CSV',downloadCsv,slug==='dashboard'||slug==='settings')}{button('????? / PDF',()=>window.print())}</div>
    {!['dashboard','settings'].includes(slug)&&<div className="flex gap-3"><input className={inputClass} placeholder="?????" aria-label="?????" value={search} onChange={e=>setSearch(e.target.value)}/><select className={inputClass} aria-label="?????" value={status} onChange={e=>setStatus(e.target.value)}>{['all',...(slug==='stock'?['active','inactive']:[...new Set(rows.map(r=>r.status).filter(Boolean))])].map(s=><option key={s}>{s}</option>)}</select></div>}
    {slug==='catalog'&&<section className="grid gap-3 sm:grid-cols-3">{meds.filter(m=>m.active).map(m=><article key={m.id} className="rounded-xl bg-white p-4 shadow">{m.imageUrl&&<img src={m.imageUrl} alt={m.name} className="h-28 w-full object-contain"/>}<strong>{m.name}</strong><p>{m.remaining} {m.unit}</p>{button('?????????????????',()=>{if(!form)open();setSelection(old=>old.some(i=>i.medicineId===m.id)?old.map(i=>i.medicineId===m.id?{...i,quantity:i.quantity+1}:i):[...old,{medicineId:m.id,quantity:1}]);})}</article>)}</section>}
    {form&&<form onSubmit={save} className="rounded-2xl border bg-white p-5 shadow print:hidden"><h2 className="mb-4 text-xl font-semibold">{form.id?'?????':'???????????'}</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([key,label,type='text',options])=>{
      if(type==='faculty')options=references.filter(f=>f.active).map(f=>f.code);
      if(type==='branch')options=references.filter(f=>f.active&&(!form.faculty||form.faculty==='all'||f.code===form.faculty)).flatMap(f=>f.branches.filter((b:Row)=>b.active).map((b:Row)=>b.name));
      const required=['name','firstName','lastName','unit','fullName','dueDate','date','documentTitle'].includes(key)||key==='symptom'&&slug==='infirmary-visit'||key==='hospitalName'&&form.status==='refer';
      return <label key={key}>{label}{required?' *':''}{options?<select className={inputClass} required={required} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value,...(key==='faculty'?{branch:''}:{})})}><option value="">?????</option>{options.map(o=><option key={o} value={o}>{type==='faculty'?references.find(f=>f.code===o)?.name:o}</option>)}</select>:<input className={inputClass} required={required} type={type} min={type==='number'?0:undefined} step={key==='weight'?'any':1} value={form[key]??''} onChange={e=>setForm({...form,[key]:type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value})}/>}</label>;
    })}</div>
    {slug==='stock'&&<div className="my-4"><label>?????<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setMessage('?????????????? 2 MiB');return;}const reader=new FileReader();reader.onload=()=>setForm(prev=>({...prev,image:reader.result}));reader.readAsDataURL(file);}}/></label>{(form.image||form.imageUrl)&&<img className="h-28" src={form.image||form.imageUrl} alt="?????"/>}{button('?????',()=>setForm({...form,image:null,imageUrl:null}))}</div>}
    {['infirmary-visit','borrow-return','catalog'].includes(slug)&&<fieldset className="my-5"><legend>????????????????</legend>{selection.map((item,index)=><div key={index} className="my-2 flex gap-2"><select className={inputClass} aria-label={'?? '+(index+1)} required value={item.medicineId} onChange={e=>setSelection(old=>old.map((i,n)=>n===index?{...i,medicineId:e.target.value}:i))}><option value="">???????</option>{meds.filter(m=>m.active||m.id===item.medicineId).map(m=><option key={m.id} value={m.id} disabled={slug!=='catalog'&&m.id!==item.medicineId&&(!medicineOptions.includes(m))}>{m.name} ? ????? {m.remaining} {m.unit}</option>)}</select><input className={inputClass} aria-label={'????? '+(index+1)} type="number" min="1" required value={item.quantity} onChange={e=>setSelection(old=>old.map((i,n)=>n===index?{...i,quantity:Number(e.target.value)}:i))}/>{button('?????',()=>setSelection(old=>old.filter((_,n)=>n!==index)))}</div>)}{button('???????',()=>setSelection(old=>[...old,{medicineId:'',quantity:1}]))}</fieldset>}
    <div className="mt-5 flex gap-3"><button disabled={busy} className="rounded-lg bg-cyan-800 px-5 py-2 text-white">??????</button>{button('??????',()=>setForm(null))}</div></form>}
    {!['dashboard','settings'].includes(slug)&&<section className="overflow-x-auto rounded-xl bg-white p-4 shadow"><table className="w-full text-left"><thead><tr><th>?????? / ??????</th><th>??????????</th><th>????? / ???</th><th className="print:hidden">??????</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} className="border-t align-top"><td className="p-3">{row.name||row.fullName||[row.firstName,row.lastName].filter(Boolean).join(' ')||row.documentTitle||row.medicine?.name||row.id}<small className="block">{row.date||row.createdAt&&new Date(row.createdAt).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</small></td><td className="p-3">{row.symptom||row.reason||row.affiliation}{line(row)&&<p>{line(row)}</p>}{row.imageUrl&&<a className="block text-cyan-700" target="_blank" rel="noreferrer" href={row.imageUrl}>?????????</a>}</td><td className="p-3">{slug==='stock'?`${row.remaining} ${row.unit} / ??????? ${row.total}${row.active?'':' (???????)'}`:row.status||row.colorId||row.source}</td><td className="flex flex-wrap gap-2 p-3 print:hidden">{button('??????????',()=>setDetail(row))}{['stock','infirmary-visit'].includes(slug)&&button('?????',()=>open(row))}{slug==='stock'&&row.active&&button('???????',()=>{if(confirm('????????????????????'))work(()=>mutate('medicines/'+row.id,'DELETE',{}));})}{slug==='catalog'&&button('??',()=>{if(confirm('????????????????'))work(()=>mutate('catalog-orders/'+row.id,'DELETE',{}));})}{slug==='borrow-return'&&row.items.length>0&&<>{button('?????????',()=>{setDetail({...row,returning:true});setSelection(row.items.map((i:Row)=>({medicineId:i.medicineId,quantity:i.quantity})));})}{button('??????????',()=>{const date=prompt('??????????????? YYYY-MM-DD',row.dueDate.slice(0,10));if(date)work(()=>mutate('loans/'+row.id,'PATCH',{dueDate:date}));})}</>}</td></tr>)}</tbody></table>{!visible.length&&<p className="p-5">???????????</p>}</section>}
    {detail&&<section className="rounded-xl border bg-white p-5"><h2 className="text-xl">??????????</h2>{Object.entries(detail).filter(([k,v])=>!['id','image','imageData','returning'].includes(k)&&v!==null&&typeof v!=='object').map(([k,v])=><p key={k}><strong>{k}: </strong>{String(v)}</p>)}{line(detail)&&<p>{line(detail)}</p>}{detail.returnHistory?.map((r:Row,i:number)=><p key={i}>??? {r.date}: {r.items.map((x:Row)=>`${x.name} ${x.quantity} ${x.unit}`).join(', ')}</p>)}{detail.returning&&<form onSubmit={e=>{e.preventDefault();work(async()=>{await mutate('loans/'+detail.id+'/returns','POST',{items:selection.filter(i=>i.quantity>0)});setDetail(null);});}}>{selection.map((item,index)=><label className="block" key={item.medicineId}>{detail.items.find((i:Row)=>i.medicineId===item.medicineId)?.name}<input className={inputClass} type="number" min="0" max={detail.items.find((i:Row)=>i.medicineId===item.medicineId)?.quantity} value={item.quantity} onChange={e=>setSelection(old=>old.map((i,n)=>n===index?{...i,quantity:Number(e.target.value)}:i))}/></label>)}<button disabled={busy} className="my-3 rounded bg-cyan-800 p-2 text-white">?????????</button></form>}{button('?????????????',()=>setDetail(null))}</section>}
    {slug==='dashboard'&&<><div className="flex flex-wrap gap-4"><label>?????<input className={inputClass} type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>???<input className={inputClass} type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>????????<select className={inputClass} value={faculty} onChange={e=>{setFaculty(e.target.value);setBranch('all');}}><option value="all">???????</option>{references.map(f=><option key={f.id} value={f.code}>{f.name}</option>)}</select></label><label>????<select className={inputClass} value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">???????</option>{references.filter(f=>faculty==='all'||f.code===faculty).flatMap(f=>f.branches).map((b:Row)=><option key={b.id}>{b.name}</option>)}</select></label></div>{summary&&<div className="grid gap-4 md:grid-cols-2"><section className="rounded-xl bg-white p-5"><h2>????????? {summary.totalVisits} ?????</h2><p>??? {summary.gender.male} ? ???? {summary.gender.female} ? ???? ? {summary.gender.other}</p><h3>???????</h3>{summary.trend.map((t:Row)=><div key={t.date} className="flex gap-2 text-sm"><span>{t.date}</span><div className="bg-cyan-500" style={{width:Math.max(1,t.count*10)+'px'}}/><span>{t.count}</span></div>)}</section><section className="rounded-xl bg-white p-5"><h2>???????????????</h2>{summary.topMedicines.map((m:Row)=><p key={m.medicineId}>{m.name} ? {m.count} ????? ? {Object.entries(m.quantities).map(([u,q])=>`${q} ${u}`).join(', ')}</p>)}</section><section className="rounded-xl bg-white p-5"><h2>?????</h2>{summary.symptoms.map((s:Row)=><p key={s.name}>{s.name}: {s.count}</p>)}</section><section className="rounded-xl bg-white p-5"><h2>?????? {summary.referrals.count}</h2>{summary.referrals.hospitals.map((s:Row)=><p key={s.name}>{s.name}: {s.count}</p>)}</section><section className="rounded-xl bg-white p-5"><h2>????????????????</h2>{summary.stock.map((s:Row)=><p key={s.id}>{s.name} ? {s.remaining} {s.unit} ? {s.status}</p>)}</section><section className="rounded-xl bg-white p-5"><h2>?????????? / ???????</h2><p>{summary.orders.length} ?????????? ? {summary.loans.filter((l:Row)=>l.items.length).length} ?????????????</p></section></div>}</>}
    {slug==='settings'&&user?.role==='ADMIN'&&<><form className="flex flex-wrap gap-3 rounded-xl bg-white p-5" onSubmit={e=>{e.preventDefault();work(()=>mutate('settings/'+(refFaculty?'branches':'faculties'),'POST',{name:refName,code:refCode,facultyId:refFaculty}));}}><select aria-label="?????????????????????" value={refFaculty} onChange={e=>setRefFaculty(e.target.value)}><option value="">?????????????</option>{references.filter(f=>f.active).map(f=><option key={f.id} value={f.id}>??????????? {f.name}</option>)}</select><input aria-label="????" placeholder="????" required value={refName} onChange={e=>setRefName(e.target.value)}/>{!refFaculty&&<input aria-label="????????????" placeholder="???? ???? engineering" required maxLength={32} value={refCode} onChange={e=>setRefCode(e.target.value)}/>}<button disabled={busy}>?????</button></form><section className="rounded-xl bg-white p-5"><h2>???????????????</h2>{references.map(f=><div key={f.id} className="my-3"><strong>{f.name}</strong> {button(f.active?'???????':'???????',()=>work(()=>mutate('settings/faculties/'+f.id,'PATCH',{active:!f.active})))}{f.branches.map((b:Row)=><p key={b.id} className="ml-4">{b.name} {button(b.active?'???????':'???????',()=>work(()=>mutate('settings/branches/'+b.id,'PATCH',{active:!b.active})))}</p>)}</div>)}</section><section className="rounded-xl bg-white p-5"><h2>?????</h2>{users.map(u=><div key={u.id} className="my-3 flex flex-wrap gap-3"><span>{u.email} ? {u.role} ? {u.active?'???????':'?????'}</span>{button('?????????????',()=>work(()=>mutate('admin/users/'+u.id,'PATCH',{role:u.role==='ADMIN'?'NURSE':'ADMIN',active:u.active})))}{button(u.active?'?????':'???????',()=>work(()=>mutate('admin/users/'+u.id,'PATCH',{role:u.role,active:!u.active})))}</div>)}</section><section className="rounded-xl bg-white p-5"><h2>Audit / ????????????</h2>{audit.map(a=><p key={a.id}>{new Date(a.createdAt).toLocaleString('th-TH')} ? {a.action} {a.entity} ? {a.actorId||'system'}</p>)}{audit.length>=100&&button('?????????',()=>{api<Row[]>('admin/audit?limit=100&cursor='+audit.at(-1)!.id).then(more=>setAudit(old=>[...old,...more])).catch(e=>setMessage(e.message));})}</section></>}
    </>}
  </main>;
}
