BEGIN;

-- Stable, per-table old-to-new maps keep all existing foreign-key relationships.
CREATE TEMP TABLE _user_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM "User";
CREATE TEMP TABLE _duty_shift_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM "DutyShift";
CREATE TEMP TABLE _patient_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM patients;
CREATE TEMP TABLE _patient_medication_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM patient_medications;
CREATE TEMP TABLE _borrow_record_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM borrow_records;
CREATE TEMP TABLE _borrow_item_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM borrow_items;
CREATE TEMP TABLE _borrow_return_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM borrow_returns;
CREATE TEMP TABLE _otp_ids AS SELECT id AS old_id, row_number() OVER (ORDER BY id)::INTEGER AS new_id FROM "PasswordResetOtp";
CREATE TEMP TABLE _nurse_ids AS SELECT "fullName" AS old_id, row_number() OVER (ORDER BY "fullName")::INTEGER AS new_id FROM "Nurse";
CREATE TEMP TABLE _legacy_storage_ids AS SELECT key AS old_id, row_number() OVER (ORDER BY key)::INTEGER AS new_id FROM "LegacyStorage";

ALTER TABLE "User" ADD COLUMN id_new SERIAL;
ALTER TABLE "DutyShift" ADD COLUMN id_new SERIAL;
ALTER TABLE patients ADD COLUMN id_new SERIAL;
ALTER TABLE patient_medications ADD COLUMN id_new SERIAL;
ALTER TABLE borrow_records ADD COLUMN id_new SERIAL;
ALTER TABLE borrow_items ADD COLUMN id_new SERIAL;
ALTER TABLE borrow_returns ADD COLUMN id_new SERIAL;
ALTER TABLE "PasswordResetOtp" ADD COLUMN id_new SERIAL;
ALTER TABLE "Nurse" ADD COLUMN id_new SERIAL;
ALTER TABLE "LegacyStorage" ADD COLUMN id_new SERIAL;

UPDATE "User" t SET id_new = m.new_id FROM _user_ids m WHERE t.id = m.old_id;
UPDATE "DutyShift" t SET id_new = m.new_id FROM _duty_shift_ids m WHERE t.id = m.old_id;
UPDATE patients t SET id_new = m.new_id FROM _patient_ids m WHERE t.id = m.old_id;
UPDATE patient_medications t SET id_new = m.new_id FROM _patient_medication_ids m WHERE t.id = m.old_id;
UPDATE borrow_records t SET id_new = m.new_id FROM _borrow_record_ids m WHERE t.id = m.old_id;
UPDATE borrow_items t SET id_new = m.new_id FROM _borrow_item_ids m WHERE t.id = m.old_id;
UPDATE borrow_returns t SET id_new = m.new_id FROM _borrow_return_ids m WHERE t.id = m.old_id;
UPDATE "PasswordResetOtp" t SET id_new = m.new_id FROM _otp_ids m WHERE t.id = m.old_id;
UPDATE "Nurse" t SET id_new = m.new_id FROM _nurse_ids m WHERE t."fullName" = m.old_id;
UPDATE "LegacyStorage" t SET id_new = m.new_id FROM _legacy_storage_ids m WHERE t.key = m.old_id;

ALTER TABLE "DutyShift" ADD COLUMN user_id_new INTEGER;
UPDATE "DutyShift" t SET user_id_new = m.new_id FROM _user_ids m WHERE t."userId" = m.old_id;
ALTER TABLE patients ADD COLUMN created_by_id_new INTEGER;
ALTER TABLE patients ADD COLUMN responsible_user_id_new INTEGER;
UPDATE patients t SET created_by_id_new = m.new_id FROM _user_ids m WHERE t.created_by_id = m.old_id;
UPDATE patients t SET responsible_user_id_new = m.new_id FROM _user_ids m WHERE t.responsible_user_id = m.old_id;
ALTER TABLE patient_medications ADD COLUMN patient_id_new INTEGER;
UPDATE patient_medications t SET patient_id_new = m.new_id FROM _patient_ids m WHERE t.patient_id = m.old_id;
ALTER TABLE borrow_items ADD COLUMN borrow_record_id_new INTEGER;
UPDATE borrow_items t SET borrow_record_id_new = m.new_id FROM _borrow_record_ids m WHERE t.borrow_record_id = m.old_id;
ALTER TABLE borrow_returns ADD COLUMN borrow_item_id_new INTEGER;
UPDATE borrow_returns t SET borrow_item_id_new = m.new_id FROM _borrow_item_ids m WHERE t.borrow_item_id = m.old_id;

ALTER TABLE "DutyShift" DROP CONSTRAINT "DutyShift_userId_fkey";
ALTER TABLE patients DROP CONSTRAINT patients_created_by_id_fkey;
ALTER TABLE patients DROP CONSTRAINT patients_responsible_user_id_fkey;
ALTER TABLE patient_medications DROP CONSTRAINT patient_medications_patient_id_fkey;
ALTER TABLE borrow_items DROP CONSTRAINT borrow_items_borrow_record_id_fkey;
ALTER TABLE borrow_returns DROP CONSTRAINT borrow_returns_borrow_item_id_fkey;

ALTER TABLE "User" DROP CONSTRAINT "User_pkey";
ALTER TABLE "DutyShift" DROP CONSTRAINT "DutyShift_pkey";
ALTER TABLE patients DROP CONSTRAINT patients_pkey;
ALTER TABLE patient_medications DROP CONSTRAINT patient_medications_pkey;
ALTER TABLE borrow_records DROP CONSTRAINT borrow_records_pkey;
ALTER TABLE borrow_items DROP CONSTRAINT borrow_items_pkey;
ALTER TABLE borrow_returns DROP CONSTRAINT borrow_returns_pkey;
ALTER TABLE "PasswordResetOtp" DROP CONSTRAINT "PasswordResetOtp_pkey";
ALTER TABLE "Nurse" DROP CONSTRAINT "Nurse_pkey";
ALTER TABLE "LegacyStorage" DROP CONSTRAINT "LegacyStorage_pkey";

ALTER TABLE "User" DROP COLUMN id;
ALTER TABLE "User" RENAME COLUMN id_new TO id;
ALTER TABLE "DutyShift" DROP COLUMN id;
ALTER TABLE "DutyShift" RENAME COLUMN id_new TO id;
ALTER TABLE "DutyShift" DROP COLUMN "userId";
ALTER TABLE "DutyShift" RENAME COLUMN user_id_new TO "userId";
ALTER TABLE patients DROP COLUMN id;
ALTER TABLE patients RENAME COLUMN id_new TO id;
ALTER TABLE patients DROP COLUMN created_by_id;
ALTER TABLE patients RENAME COLUMN created_by_id_new TO created_by_id;
ALTER TABLE patients DROP COLUMN responsible_user_id;
ALTER TABLE patients RENAME COLUMN responsible_user_id_new TO responsible_user_id;
ALTER TABLE patient_medications DROP COLUMN id;
ALTER TABLE patient_medications RENAME COLUMN id_new TO id;
ALTER TABLE patient_medications DROP COLUMN patient_id;
ALTER TABLE patient_medications RENAME COLUMN patient_id_new TO patient_id;
ALTER TABLE borrow_records DROP COLUMN id;
ALTER TABLE borrow_records RENAME COLUMN id_new TO id;
ALTER TABLE borrow_items DROP COLUMN id;
ALTER TABLE borrow_items RENAME COLUMN id_new TO id;
ALTER TABLE borrow_items DROP COLUMN borrow_record_id;
ALTER TABLE borrow_items RENAME COLUMN borrow_record_id_new TO borrow_record_id;
ALTER TABLE borrow_returns DROP COLUMN id;
ALTER TABLE borrow_returns RENAME COLUMN id_new TO id;
ALTER TABLE borrow_returns DROP COLUMN borrow_item_id;
ALTER TABLE borrow_returns RENAME COLUMN borrow_item_id_new TO borrow_item_id;
ALTER TABLE "PasswordResetOtp" DROP COLUMN id;
ALTER TABLE "PasswordResetOtp" RENAME COLUMN id_new TO id;
ALTER TABLE "Nurse" RENAME COLUMN id_new TO id;
ALTER TABLE "LegacyStorage" RENAME COLUMN id_new TO id;

ALTER TABLE "User" ADD CONSTRAINT "User_pkey" PRIMARY KEY (id);
ALTER TABLE "DutyShift" ADD CONSTRAINT "DutyShift_pkey" PRIMARY KEY (id);
ALTER TABLE "DutyShift" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "DutyShift" ADD CONSTRAINT "DutyShift_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DutyShift" ADD CONSTRAINT "DutyShift_userId_date_key" UNIQUE ("userId", date);
ALTER TABLE patients ADD CONSTRAINT patients_pkey PRIMARY KEY (id);
ALTER TABLE patients ADD CONSTRAINT patients_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES "User"(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE patients ADD CONSTRAINT patients_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES "User"(id) ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX patients_created_by_id_idx ON patients (created_by_id);
CREATE INDEX patients_responsible_user_id_idx ON patients (responsible_user_id);
ALTER TABLE patient_medications ADD CONSTRAINT patient_medications_pkey PRIMARY KEY (id);
ALTER TABLE patient_medications ALTER COLUMN patient_id SET NOT NULL;
ALTER TABLE patient_medications ADD CONSTRAINT patient_medications_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX patient_medications_patient_id_dispensed_at_idx ON patient_medications (patient_id, dispensed_at);
ALTER TABLE borrow_records ADD CONSTRAINT borrow_records_pkey PRIMARY KEY (id);
ALTER TABLE borrow_items ADD CONSTRAINT borrow_items_pkey PRIMARY KEY (id);
ALTER TABLE borrow_items ALTER COLUMN borrow_record_id SET NOT NULL;
ALTER TABLE borrow_items ADD CONSTRAINT borrow_items_borrow_record_id_fkey FOREIGN KEY (borrow_record_id) REFERENCES borrow_records(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE borrow_items ADD CONSTRAINT borrow_items_borrow_record_id_catalog_code_key UNIQUE (borrow_record_id, catalog_code);
ALTER TABLE borrow_returns ADD CONSTRAINT borrow_returns_pkey PRIMARY KEY (id);
ALTER TABLE borrow_returns ALTER COLUMN borrow_item_id SET NOT NULL;
ALTER TABLE borrow_returns ADD CONSTRAINT borrow_returns_borrow_item_id_fkey FOREIGN KEY (borrow_item_id) REFERENCES borrow_items(id) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX borrow_returns_borrow_item_id_returned_at_idx ON borrow_returns (borrow_item_id, returned_at);
ALTER TABLE "PasswordResetOtp" ADD CONSTRAINT "PasswordResetOtp_pkey" PRIMARY KEY (id);
ALTER TABLE "Nurse" ADD CONSTRAINT "Nurse_pkey" PRIMARY KEY (id);
ALTER TABLE "Nurse" ADD CONSTRAINT "Nurse_fullName_key" UNIQUE ("fullName");
ALTER TABLE "LegacyStorage" ADD CONSTRAINT "LegacyStorage_pkey" PRIMARY KEY (id);
ALTER TABLE "LegacyStorage" ADD CONSTRAINT "LegacyStorage_key_key" UNIQUE (key);

COMMIT;
